#!/bin/bash

#PBS -l nodes=1:ppn=16,walltime=20:00:00,mem=100GB
#PBS -N T2_Counts_sort
#PBS -M gah324@nyu.edu
#PBS -m e
#PBS -e localhost:/scratch/gah324/log/e_counts_T2
#PBS -o localhost:/scratch/gah324/log/o_counts_T2


module purge

cd /scratch/gah324/AppliedGenomics/Prostat_Project/SRAs/SRP036848/T2_Bam

module load samtools/intel/1.2

samtools sort -@ 16 *798* 798.sorted
samtools sort -@ 16 *800* 800.sorted
samtools sort -@ 16 *805* 805.sorted
samtools sort -@ 16 *806* 806.sorted
samtools sort -@ 16 *807* 807.sorted
samtools sort -@ 16 *808* 808.sorted
samtools sort -@ 16 *809* 809.sorted
samtools sort -@ 16 *811* 811.sorted
samtools sort -@ 16 *815* 815.sorted
samtools sort -@ 16 *816* 816.sorted
samtools sort -@ 16 *819* 819.sorted
samtools sort -@ 16 *820* 820.sorted
samtools sort -@ 16 *824* 824.sorted
samtools sort -@ 16 *825* 825.sorted
samtools sort -@ 16 *827* 827.sorted
samtools sort -@ 16 *829* 829.sorted

mv *.sorted ../../STAR/SRP036848/.

module purge

cd /scratch/gah324/AppliedGenomics/Prostat_Project/SRAs/STAR/SRP036848/

module load pysam/intel/0.7.5
module load htseq/intel/0.6.1

mkdir counts
mkdir counts/T2

htseq-count -f bam 798.sorted.bam ../../Ref_Genome_hg19/genes.gtf > counts/T2/798.count.txt
htseq-count -f bam 800.sorted.bam ../../Ref_Genome_hg19/genes.gtf > counts/T2/798.count.txt
htseq-count -f bam 805.sorted.bam ../../Ref_Genome_hg19/genes.gtf > counts/T2/798.count.txt
htseq-count -f bam 806.sorted.bam ../../Ref_Genome_hg19/genes.gtf > counts/T2/798.count.txt
htseq-count -f bam 807.sorted.bam ../../Ref_Genome_hg19/genes.gtf > counts/T2/798.count.txt
htseq-count -f bam 808.sorted.bam ../../Ref_Genome_hg19/genes.gtf > counts/T2/798.count.txt
htseq-count -f bam 809.sorted.bam ../../Ref_Genome_hg19/genes.gtf > counts/T2/798.count.txt
htseq-count -f bam 811.sorted.bam ../../Ref_Genome_hg19/genes.gtf > counts/T2/798.count.txt
htseq-count -f bam 815.sorted.bam ../../Ref_Genome_hg19/genes.gtf > counts/T2/798.count.txt
htseq-count -f bam 816.sorted.bam ../../Ref_Genome_hg19/genes.gtf > counts/T2/798.count.txt
htseq-count -f bam 819.sorted.bam ../../Ref_Genome_hg19/genes.gtf > counts/T2/798.count.txt
htseq-count -f bam 820.sorted.bam ../../Ref_Genome_hg19/genes.gtf > counts/T2/798.count.txt
htseq-count -f bam 824.sorted.bam ../../Ref_Genome_hg19/genes.gtf > counts/T2/798.count.txt
htseq-count -f bam 825.sorted.bam ../../Ref_Genome_hg19/genes.gtf > counts/T2/798.count.txt 
htseq-count -f bam 827.sorted.bam ../../Ref_Genome_hg19/genes.gtf > counts/T2/798.count.txt
htseq-count -f bam 829.sorted.bam ../../Ref_Genome_hg19/genes.gtf > counts/T2/798.count.txt

